### ISSUE TITLE
Recognizing CLI commands in example

### ISSUE THREAD

**Issue by vfulco** [rupakg/sls-blog#1]
New to serverless.com. Have run 'hello world' and one other toy example fine using sls deploy and AWS lambda.

Trying to get up the curve and learn components with this serverless hugo example. When I use 'components deploy' in the dir with my serverless.yml, my system comes back with command not found. Using zsh on Ubuntu 18.04, Node Version:11.2.0, Serverless Version: 1.33.2

Thanks in advance.

**Comment by vfulco** [comment]
There is some screwy path dependency issue I can't resolve with softlinks and node.js.  Running now using "npx components deploy"

**Comment by rupakg** [comment]
@vfulco it should work if the `serverless components` are installed properly. Or you can even clone the repo and then run it locally using `./components deploy`. If it still does not work you can open an issue on the `serverless/components` repo. Good luck!
